(setq emacs-configuration-root-dir "~/.emacs.d/")
(load (concat emacs-configuration-root-dir "env-default.el"))
(if (file-exists-p (concat emacs-configuration-root-dir "env.el"))
  (load (concat emacs-configuration-root-dir "env.el")))

;; set right-little-finger-key based on keyboard layout
(if (and (boundp 'keyboard-layout) (string= keyboard-layout "sv"))
    (setq right-little-finger-key "ö")
  (setq right-little-finger-key ";"))

(add-to-list 'load-path (concat emacs-configuration-root-dir "init"))
(require 'init-package)
(require 'init-helm)
(require 'init-company)
(require 'init-edit)
(require 'init-buffer)
(require 'init-view)
(require 'init-term)
(require 'init-eshell)
(require 'init-dired)
(require 'init-org)
(require 'init-remote)
(require 'init-project)
(require 'init-programming)
(require 'init-elisp)
(require 'init-c)
(require 'init-erlang)
(require 'init-magit)
(require 'init-chinese)
(require 'init-misc)
(require 'init-appearance)

;; desktop save
(desktop-save-mode 1)
(setq desktop-restore-eager t)
(setq desktop-files-not-to-save "^$")

;;(add-to-list 'load-path (concat emacs-configuration-root-dir "workgroups2/src"))
;;(require 'workgroups2)
;;(setq wg-mode-line-disable t)
;;(setq wg-modeline-string "")
;;(workgroups-mode 1)

;;(add-hook 'emacs-startup-hook #'(lambda () (wg-reload-session)))
