(add-to-list 'load-path (expand-file-name "init" user-emacs-directory))
(require 'init-env)
(require 'init-package)
(require 'init-helm)
(require 'init-company)
(require 'init-edit)
(require 'init-buffer)
(require 'init-view)
(require 'init-term)
(require 'init-eshell)
(require 'init-dired)
(require 'init-org)
(require 'init-remote)
(require 'init-project)
(require 'init-programming)
(require 'init-elisp)
(require 'init-c)
(require 'init-erlang)
(require 'init-magit)
(require 'init-chinese)
(require 'init-session)
(require 'init-misc)
(require 'init-appearance)

(workgroups-mode 1)
