
;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(add-to-list 'load-path (expand-file-name "lisp" user-emacs-directory))
(require 'init-package)
(require 'init-env)
(require 'init-basic)
;;(require 'init-helm)
(require 'init-ivy)
(require 'init-company)
(require 'init-buffer)
(require 'init-window)
(require 'init-edit)
(require 'init-view)
;;(require 'init-term)
(require 'init-eshell)
;;(require 'init-dired)
;;(require 'init-org)
(require 'init-remote)
(require 'init-programming)
(require 'init-project)
(require 'init-elisp)
(require 'init-cc)
(require 'init-c-cpp)
;;(require 'init-python)
;;(require 'init-erlang)
(require 'init-git)
;;(require 'init-email)
;;(require 'init-chinese)
(require 'init-misc)
(require 'init-session)
(require 'init-keybinding)
